version: '3.9'
services:
  db:
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file: .env

  api:
    build: ./
    ports:
      - 8080:8080
    volumes:
      - ./src:/src
    env_file: .env
