swagger: "2.0"
info:
  title: Flask API
  description: Dockerized Flask API connected to MongoDB database
  version: 1.0.0

host: api
basePath: /
schemas:
  - http

paths:
  /add: 
    post:
      summary: Add key-value pair to database
      parameters:
        - in: query
          name: key
          description: Item key
        - in: query
          name: value
          description: Item value
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        201:
          description: Created
        400:
          description: Key or Value is required
  /update: 
    put:
      summary: Update value by key
      parameters:
        - in: query
          name: key
          description: Item key
        - in: query
          name: new_value
          description:
            Item new value
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        200:
          description: Successful operation
        400:
          description: New value is required
        404:
          description: Key not found
  /read/{key}:
    get:
      summary: Show value by key
      parameters:
        - in: path
          name: key
          required: true
          description: Item key
      produces:
        - application/json
      responses:
        200:
          description: Successful operation
        404:
          description: Key not found